Support input array is empty
otiai10/cwl.go pull request #35
Opened 2018-07-24 07:31 UTC by manabuishii

for conformance test 127
empty-array-input.cwl, empty-array-job.json

2018-07-24 07:39 UTC, otiai10 commented
https://github.com/manabuishii/cwl.go/blob/84d3aaee6eee641fc5d67fb1ca69d7e95f94c43f/input.go#L233-L254

ここなんですけど、まだ僕らが `Types` 長さゼロがありうると思っていたころの名残なので、ここまとめて `Types[0].Type` でswitchするようにしたほうがいいかも

2018-07-27 03:36 UTC, otiai10 requested changes

2018-07-27 03:36 UTC, otiai10 commented on input.go
> +		if len(input.Types) == 1 {
`input.Types[0].Type` が `null` の場合って、現状けっこう許容されている && 今後もしかしたらなくなるかも、という見地から、この `case` の中は、別途 `Input` のメソッドとして切り出しておいたほうがいいかもしれないですね。

```go
// {{{
    case "null":
        return input.flatten◯◯Typed()
// }}}

func (input *Input) flatten◯◯Typed() []string {
  // ...
}
// みたいな
```

ところで、 `input.Types[0].Type == "null"` という表現は、どういう意味を持つんですか？「◯◯」の命名に関わるので。（1週間ぶり3回目ぐらいの質問で申し訳ないです :bow: ）

2018-07-27 03:43 UTC, otiai10 commented on input.go
> +		if len(input.Types) == 1 {
returnしてもいいのかな。ここでreturnせず、下の Binding とかの処理までいかせたいケースってあるんだろうか。

2018-07-27 04:53 UTC, manabuishii commented on input.go
> +		if len(input.Types) == 1 {
上のコメント：
配列の場合の意味については、仕様をみていますが、まだ該当箇所がわかっていないので、わかりしだいコメントします。

下のコメント：
`type` が `null` だけ（配列ではなく１つのみ）の場合のreturn については、以下を参照しました。
[5.1.2 CommandLineBinding](https://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineBinding) によると、 `null` の場合は、何もしなくてよいと解釈しました。

```
null: Add nothing.
```

2018-08-31 02:48 UTC, otiai10 approved these changes

2018-08-31 02:48 UTC, merged